uv_led_detector:
  camera_input_topics: ["/my_camera/pylon_ros2_camera_node/image_raw"] 
  detected_points_topics: ["/detected_points_out"]
  use_gpu: true # GPU option is preferable
  gui: false # TODO: remove
  use_masks: false # not implemented yet
  fast_ring_size: 5 # only 3, 4 or 5 are supported
  threshold: 50 # minimum pixel brightness to be considered
  threshold_diff: 25 # minimum brightness difference from surrounding pixels
  threshold_sun: 150 # brightness threshold for candidate sun pixels
  threshold_sun_dist: 25 # max pixel distance to classify a pixel as sun-affected
  threshold_sun_merge: 20 # max pixel distance for merging sun pixel clusters
  initial_delay: 2.0 # safety initial delay in seconds before starting detection
  publish_sun_points: false

blink_processor:
  pattern_file: "/blinking_sequences/blinking_sequence.txt" # path to the file with blinking patterns
  allowed_BER_per_sequence: 0 # allowed Bit Error Rate per blinking sequence
  polynomial_degree: 4 # degree of the polynomial for trajectory fitting
  decay_factor: 0.2 # the factor for exponential decay of the weights of older detections in the trajectory calculation
  stored_seq_len_factor: 20 # the multiplication factor how long the sequence should be for calculating the trajectory   
  confidence_probability_percentage: 95 # statistical confidence level used to compute the prediction interval width
  max_buffer_lenght: 100 # maximum number of tracked objects in the buffer (max number of t-series)
  min_prediction_tol_px: 3 # minimum pixel tolerance added to regression uncertainty to prevent zero-width prediction intervals
  max_zeros_consecutive: 10 # maximum consecutive zeros in the recorded sequence (t-series) for it to be still considered valid
