uav_name: "uav1"
initial_delay: 2.0
camera_input_topics: ["/my_camera/pylon_ros2_camera_node/image_raw"] # move to launch
detected_points_topics: ["/detected_points_out"] # move to launch
publish_sun_points: true

uv_led_detector:
  use_gpu: true
  gui: false
  use_masks: false
  fast_ring_size: 5 # only 3, 4 or 5 are supported
  threshold: 50 # minimum pixel brightness to be considered
  threshold_diff: 25 # minimum brightness difference from surrounding pixels
  threshold_sun: 150 # brightness threshold for candidate sun pixels
  threshold_sun_dist: 25 # max pixel distance to classify a pixel as sun-affected
  threshold_sun_merge: 20 # max pixel distance for merging sun pixel clusters
