<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>uvdar_ros</name>
  <version>1.0.0</version>
  <description>uvdar_ros</description>

  <maintainer email="viktor.walter@fel.cvut.cz">Viktor Walter</maintainer>
  <maintainer email="merva@fly4future.com">Tomas Merva</maintainer>

  <license>BSD 3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_ros</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>cv_bridge</depend>
  <depend>image_transport</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>tf2_eigen</depend>
  <depend>eigen</depend>
  <depend>ament_index_cpp</depend>
  
  <depend>mrs_lib</depend>
  <depend>mrs_msgs</depend>
  <depend>uvdar</depend>
  <depend>uvdar_ros_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
